services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=colorado63
      - POSTGRES_USER=breno
      - POSTGRES_DB=weather_etl
    ports:
      - 1818:5432
    restart: unless-stopped
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network
  
  apache:
    image: apache/airflow:2.9.0
    container_name: airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://breno:colorado63@postgres:5432/airflow
      - PYTHONPATH= /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
    ports:
      - 1919:8080
    command: standalone
    depends_on:
      - postgres
    networks:
      - etl_network
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - 2020:3000
    depends_on:
      - postgres
    networks:
      - etl_network

networks:
  etl_network:
    driver: bridge

volumes:
  postgres_data:
  